POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@gmail.com",
  "password": "123"
}

### Test - second user register
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
"name": "Test User 3",
"email": "230103179@sdu.edu.kz",
"password": "1234"
}


### Login - success
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123"
}

### Login - wrong password
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "wrong"
}

### Login - missing field
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com"
}

### Login - unknown user
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "unknown@gmail.com",
  "password": "123"
}

### Protected test - no token
GET http://localhost:3001/api/auth/me-test

### Protected test - valid token
GET http://localhost:3001/api/auth/me-test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MTI4OTgzNCwiZXhwIjoxNzgxMzc2MjM0fQ.QRfDZ9YKPxUQ5oNkHRVKX28Qlx1YztbAUzD8L7QTS6w


### Protected test - users validation
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MTI4OTgzNCwiZXhwIjoxNzgxMzc2MjM0fQ.QRfDZ9YKPxUQ5oNkHRVKX28Qlx1YztbAUzD8L7QTS6w

### Test - block users array
POST http://localhost:3001/api/users/block
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MTM0Mjc4MywiZXhwIjoxNzgxNDI5MTgzfQ.29ek85W7QVG5orqHRsh6bmcMtMuPjyovN5G3eFuiGjU
Content-Type: application/json

{
  "ids": [3]
}

### Test - Invalid body
POST http://localhost:3001/api/users/block
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MTI4OTgzNCwiZXhwIjoxNzgxMzc2MjM0fQ.QRfDZ9YKPxUQ5oNkHRVKX28Qlx1YztbAUzD8L7QTS6w
Content-Type: application/json

{
"ids": []
}

### Test - Unblock
POST http://localhost:3001/api/users/unblock
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MTM0Mjc4MywiZXhwIjoxNzgxNDI5MTgzfQ.29ek85W7QVG5orqHRsh6bmcMtMuPjyovN5G3eFuiGjU
Content-Type: application/json

{
"ids": [3]
}

### Test - deleting the second user
DELETE http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc4MTM0Mjc4MywiZXhwIjoxNzgxNDI5MTgzfQ.29ek85W7QVG5orqHRsh6bmcMtMuPjyovN5G3eFuiGjU
Content-Type: application/json

{
"ids": [3]
}














